#!/bin/sh

# frontend for:            cuetools, shntool, mp3splt
# optional dependencies:    flac, mac, wavpack, ttaenc
# v1.3 sen

export IFS=$'\n'


SDIR=`pwd`

if [ "$1" = "" ]
  then
    DIR=$SDIR
else
    case $1 in
        -h | --help )
            echo "Usage: cuesplit [Path]"
            echo "       The default path is the current directory."
            exit
            ;;
        * )
        DIR=$1
    esac
fi

OPTION_SHNSPLIT='flac flac -V --best -o %f -'
FORMAT_SHNSPLIT='%n - %p - %t'
FORMAT_MP3SPLT='@n - @p - @t'

echo -e "\

Directory: $DIR
________________________________________
"
cd "$DIR"
TYPE=`ls -t1`

case $TYPE in
    *.ape*)
        shnsplit -f *.cue -o "${OPTION_SHNSPLIT}" *.ape -t "${FORMAT_SHNSPLIT}" || continue
        rm -f 00*pregap* || continue
        cuetag.sh *.cue *.flac || continue
        exit
        ;;

    *.flac*)
        shnsplit -f *.cue -o "${OPTION_SHNSPLIT}" *.flac -t "${FORMAT_SHNSPLIT}" || cnotinue
        rm -f 00*pregap* || continue
        cuetag.sh *.cue *.flac || continue
        exit
        ;;

    *.mp3*)
        mp3splt -no "${FORMAT_MP3SPLT}" -c *.cue *.mp3 || continue
        cuetag.sh *.cue *.mp3
        exit
        ;;

    *.ogg*)
        mp3splt -no "${FORMAT_MP3SPLT}" -c *.cue *.ogg || continue
        cuetag.sh *.cue *.ogg || continue
        exit
        ;;

    *.tta*)
        shnsplit -f *.cue -o "${OPTION_SHNSPLIT}" *.tta -t "${FORMAT_SHNSPLIT}" || continue
        rm -f 00*pregap* || continue
        cuetag.sh *.cue *.flac || continue
        exit
        ;;

    *.wv*)
        shnsplit -f *.cue -o "${OPTION_SHNSPLIT}" *.wv -t "${FORMAT_SHNSPLIT}" || continue
        rm -f 00*pregap* || continue
        cuetag.sh *.cue *.flac || continue
        exit
        ;;

    *.wav*)
        shnsplit -f *.cue -o "${OPTION_SHNSPLIT}" *.wav -t "${FORMAT_SHNSPLIT}" || continue
        rm -f 00*pregap* || continue
        cuetag.sh *.cue *.flac || continue
        exit
        ;;

    * )
    echo "Error: Found no files to split!"
    echo "       --> APE, FLAC, MP3, OGG, TTA, WV, WAV"
esac
exit

