#!/bin/bash

# frontend for:            cuetools, shntool, mp3splt
# optional dependencies:    flac, mac, wavpack, ttaenc
# v1.3 sen

export IFS=$'\n'


SDIR=`pwd`

if [ "$1" = "" ]
  then
    DIR=$SDIR
else
    case $1 in
        -h | --help )
            echo "Usage: cuesplit [Path]"
            echo "       The default path is the current directory."
            exit
            ;;
        * )
        DIR=$1
    esac
fi

ABS_DIR=`readlink -f ${DIR}`

OPTION_SHNSPLIT='flac flac -V --best -o %f -'
FORMAT_SHNSPLIT='%n - %p - %t'
FORMAT_MP3SPLT='@n - @p - @t'

echo -e "\

Directory: $ABS_DIR
________________________________________
"
cd ${ABS_DIR}

CUE_LIST=`find "${ABS_DIR}" -name *.cue`
for CUE in ${CUE_LIST}
do
	ABS_CUE=`readlink -f ${CUE}`
	echo "ABS_CUE:"${ABS_CUE}
	TARGET=`ls -S1 ${ABS_CUE%%.cue}.* | head -n 1` || continue
	echo "target:"${TARGET}
	TARGET_DIR=$(dirname "${ABS_CUE}")
	echo "target_dir:"${TARGET_DIR}

	cd "${TARGET_DIR}"

	case "${TARGET}" in
	    *.ape*)
	        shnsplit -f "${ABS_CUE}" -o "${OPTION_SHNSPLIT}" "${TARGET}" -t "${FORMAT_SHNSPLIT}" || continue
	        rm -f 00*pregap* || continue
	        cuetag.sh "${ABS_CUE}" *.flac || continue
	        ;;

 	   *.flac*)
 	       shnsplit -f "${ABS_CUE}" -o "${OPTION_SHNSPLIT}" "${TARGET}" -t "${FORMAT_SHNSPLIT}" || continue
 	       rm -f 00*pregap* || continue
 	       cuetag.sh "${ABS_CUE}" *.flac || continue
 	       ;;

 	   *.mp3*)
 	       mp3splt -no "${FORMAT_MP3SPLT}" -c "${ABS_CUE}" "${TARGET}" || continue
 	       cuetag.sh "${ABS_CUE}" *.mp3
 	       ;;

 	   *.ogg*)
 	       mp3splt -no "${FORMAT_MP3SPLT}" -c "${ABS_CUE}" "${TARGET}" || continue
 	       cuetag.sh "${ABS_CUE}" *.ogg || continue
 	       ;;

 	   *.tta*)
 	       shnsplit -f "${ABS_CUE}" -o "${OPTION_SHNSPLIT}" "${TARGET}" -t "${FORMAT_SHNSPLIT}" || continue
 	       rm -f 00*pregap* || continue
 	       cuetag.sh "${ABS_CUE}" *.flac || continue
 	       ;;

 	   *.wv*)
 	       shnsplit -f "${ABS_CUE}" -o "${OPTION_SHNSPLIT}" "${TARGET}" -t "${FORMAT_SHNSPLIT}" || continue
 	       rm -f 00*pregap* || continue
	       cuetag.sh "${ABS_CUE}" *.flac || continue
	       ;;

	    *.wav*)
	        shnsplit -f "${ABS_CUE}" -o "${OPTION_SHNSPLIT}" "${TARGET}" -t "${FORMAT_SHNSPLIT}" || continue
	        rm -f 00*pregap* || continue
	        cuetag.sh "${ABS_CUE}" *.flac || continue
	        ;;

	    * )
	    	echo "Error: Found no files to split!"
	    	echo "       --> APE, FLAC, MP3, OGG, TTA, WV, WAV"
		;;

	esac

done

exit

